version: "3.9"

services:
  db:
    image: redis:latest
    init: true
    restart: unless-stopped
    container_name: testflinger-db

    networks:
      docker_int:
        ipv4_address: 10.172.10.13
    expose:
      - 6379
    hostname: testflinger-db

    volumes:
      - db_data:/var/lib/redis
      - db_log:/var/log/redis

    environment:
      - REDIS_REPLICATION_MODE=master

    command: [
      "redis-server",
      "--bind 0.0.0.0",
      "--maxmemory 16384mb",
      "--maxmemory-policy allkeys-lfu"
    ]

  mqtt:
    depends_on:
      - db
    build:
      context: .
      dockerfile: testflinger-mqtt
    restart: unless-stopped
    container_name: testflinger-mqtt

    networks:
      needham_ext:
        ipv4_address: 10.245.128.14
      docker_int:
        ipv4_address: 10.172.10.14
    expose:
      - 1883
      - 9001
    hostname: testflinger-mqtt

    # volumes:
    #   - ./mqtt/conf:/mosquitto/config

  api:
    depends_on:
      - mqtt
    build:
      context: .
      dockerfile: testflinger-api
    init: true
    restart: unless-stopped
    container_name: testflinger-api

    sysctls:
      net.core.somaxconn: 2048

    networks:
      needham_ext:
        ipv4_address: 10.245.128.10
      docker_int:
        ipv4_address: 10.172.10.10
    expose:
      - 8000
    hostname: testflinger-api

    volumes:
      - api_data:/data/testflinger

    environment:
      - PATH=/data/testflinger:$PATH

    command: [
      "gunicorn",
      "-b=0.0.0.0",
      "-t=0",
      "-k=gevent",
      "--worker-connections=1000",
      "testflinger:app"
    ]

  agent:
    depends_on:
      - api
    build:
      context: .
      dockerfile: testflinger-agent
    stdin_open: true
    tty: true
    restart: unless-stopped
    container_name: testflinger-agent

    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined

    networks:
      needham_ext:
        ipv4_address: 10.245.128.11
      docker_int:
        ipv4_address: 10.172.10.11
    expose:
      - 19999
    hostname: testflinger-agent

    volumes:
      - agent_data:/data/testflinger-agent
      - snappy_data:/data/snappy-device-agents
      - agent_log:/var/log/sut-agent
      # netdata volumes
      # - netdata_cache:/var/cache/netdata
      # - netdata_config:/etc/netdata
      # - netdata_lib:/var/lib/netdata
      # - /proc:/host/proc:ro
      # - /sys:/host/sys:ro
      # - /etc/os-release:/host/etc/os-release:ro

    environment:
      - PATH=/data/testflinger-agent:/data/snappy-device-agents:$PATH

    command: ["/opt/tf-entrypoint.sh"]

    # healthcheck:
    #   test: ["CMD", "ubuntu", "ping", "-h", "127.0.0.1", "--silent"]
    #   interval: 3s
    #   retries: 5
    #   start_period: 30s

  cli:
    depends_on:
      - agent
    build:
      context: .
      dockerfile: testflinger-cli
    stdin_open: true
    tty: true
    restart: unless-stopped
    container_name: testflinger-cli

    networks:
      needham_ext:
        ipv4_address: 10.245.128.12
      docker_int:
        ipv4_address: 10.172.10.12
    hostname: testflinger-cli

    volumes:
      - cli_data:/data/testflinger-cli

    environment:
      - PATH=/data/testflinger-cli:$PATH

    # command: ["/opt/tf-entrypoint.sh"]

networks:
  docker_int:
    driver: bridge
    driver_opts:
        parent: docker0
    ipam:
      config:
        - subnet: "10.172.10.1/24"

  needham_ext:
    driver: macvlan
    driver_opts:
        parent: eno2
    ipam:
      config:
        - subnet: "10.245.128.0/22"

volumes:
  db_data: {}
  db_log: {}
  api_data: {}
  agent_data: {}
  snappy_data: {}
  agent_log: {}
  cli_data: {}
  # netdata_cache: {}
  # netdata_config: {}
  # netdata_lib: {}
  loki_data: {}
  grafana_data: {}
  promtail_data: {}
