version: "3.9"

services:
  db:
    # use docker redis image
    image: redis:latest
    init: true
    restart: unless-stopped

    networks:
      docker_int:
        ipv4_address: 10.172.10.13
    expose:
      - "6379"
    hostname: testflinger-db

    volumes:
      - db_data:/var/lib/redis

    environment:
      - REDIS_REPLICATION_MODE=master

    command: [
      "redis-server",
      "--bind 0.0.0.0",
      "--maxmemory 16384mb",
      "--maxmemory-policy allkeys-lfu"
    ]

  api:
    depends_on:
      - db
    build:
      context: .
      dockerfile: testflinger-api
    init: true
    restart: unless-stopped

    sysctls:
      net.core.somaxconn: 2048

    networks:
      needham_ext:
        ipv4_address: 10.245.128.10
      docker_int:
        ipv4_address: 10.172.10.10
    expose:
      - "8000"
    hostname: testflinger-api

    volumes:
      - api_data:/data/testflinger

    environment:
      - PATH=/data/testflinger:$PATH

    command: [
      "gunicorn",
      "--bind 0.0.0.0",
      "--timeout 240",
      "--worker-class gevent",
      "--worker-connections 100",
      "--workers 3",
      "testflinger:app"
    ]

  agent:
    depends_on:
      - api
    build:
      context: .
      dockerfile: testflinger-agent
    stdin_open: true
    tty: true
    restart: unless-stopped

    networks:
      needham_ext:
        ipv4_address: 10.245.128.11
      docker_int:
        ipv4_address: 10.172.10.11
    hostname: testflinger-agent

    volumes:
      - agent_data:/data/testflinger-agent
      - snappy_data:/data/snappy-device-agents

    environment:
      - PATH=/data/testflinger-agent:/data/snappy-device-agents:$PATH

    command: ["/opt/tf-entrypoint.sh"]

    # healthcheck:
    #   test: ["CMD", "ubuntu", "ping", "-h", "127.0.0.1", "--silent"]
    #   interval: 3s
    #   retries: 5
    #   start_period: 30s

  cli:
    depends_on:
      - agent
    build:
      context: .
      dockerfile: testflinger-cli
    stdin_open: true
    tty: true
    restart: unless-stopped

    networks:
      needham_ext:
        ipv4_address: 10.245.128.12
      docker_int:
        ipv4_address: 10.172.10.12
    hostname: testflinger-cli

    volumes:
      - cli_data:/data/testflinger-cli

    environment:
      - PATH=/data/testflinger-cli:$PATH

    command: ["/opt/tf-entrypoint.sh"]

  # logstash:
  #     depends_on:
  #       - cli
  #     labels:
  #       com.example.service: "logstash"
  #       com.example.description: "For logging data"
  #     image: logstash

  #     networks:
  #       docker_int:
  #         ipv4_address: 10.172.10.14
  #     expose:
  #       - "5959"
  #     hostname: testflinger-log

  #     volumes:
  #       - log_data:/var

  #     command: "logstash -f /logstash_dir/logstash.conf"

networks:
  docker_int:
    driver: bridge
    driver_opts:
        parent: docker0
    ipam:
      config:
        - subnet: "10.172.10.1/24"

  needham_ext:
    driver: macvlan
    driver_opts:
        parent: eno2
    ipam:
      config:
        - subnet: "10.245.128.0/22"

volumes:
  db_data: {}
  api_data: {}
  agent_data: {}
  snappy_data: {}
  cli_data: {}
  # log_data: {}
