version: "2"

services:
  db:
    # use docker redis image
    image: redis

    networks:
      needham_int:
        ipv4_address: 10.1.11.12
    ports:
      - "6379:6379"
    hostname: testflinger-db

    volumes:
      - db_data:/var/lib/redis

    environment:
      - REDIS_REPLICATION_MODE=master

    command: [
      "redis-server",
      "--bind 0.0.0.0",
      "--maxmemory 4096mb",
      "--maxmemory-policy allkeys-lfu"
    ]

  api:
    depends_on:
      - db
    # build image w/ deps
    build:
      context: .
      dockerfile: testflinger-api

    networks:
      needham_int:
        ipv4_address: 10.1.11.13
    ports:
      - "8000:8000"
    hostname: testflinger-api

    volumes:
      - tf_data:/data

    environment:
      - TESTFLINGER_CONFIG=/data/testflinger/testflinger.conf

    command: "gunicorn --bind 0.0.0.0:8000 testflinger:app" 

  agent:
    depends_on:
      - api
    # build image w/ deps
    build: 
      context: .
      dockerfile: testflinger-agent

    networks:
      needham_ext:
        ipv4_address: 10.245.128.11
      needham_int:
        ipv4_address: 10.1.11.11
    hostname: testflinger-agent

    volumes:
      - tf_data:/data

    command: ["/sbin/my_init","--","setuser","app","bash"]

  snappy:
    depends_on:
      - agent
    # build image w/ deps
    build: 
      context: .
      dockerfile: testflinger-snappy

    networks:
      needham_int:
        ipv4_address: 10.1.11.14
    hostname: testflinger-snappy

    volumes:
      - tf_data:/data

  cli:
    depends_on:
      - snappy
    # build image w/ deps
    build: 
      context: .
      dockerfile: testflinger-cli

    networks:
      needham_ext:
        ipv4_address: 10.245.128.10
      needham_int:
        ipv4_address: 10.1.11.10
    hostname: testflinger-cli

    volumes:
      - tf_data:/data

    command: ["/sbin/my_init","--","setuser","app","bash"]

networks:
  needham_int:
    driver: macvlan
    driver_opts:
        parent: eno1
    ipam:
      config:
        - subnet: "10.1.10.0/23"
          gateway: 10.1.10.2

  needham_ext:
    driver: macvlan
    driver_opts:
        parent: eno2
    ipam:
      config:
        - subnet: "10.245.128.0/22"
          gateway: 10.245.128.1

volumes:
  db_data: {}
  tf_data: {}
