version: "3.8"

services:
  db:
    # use docker redis image
    image: redis
    init: true
    restart: unless-stopped

    networks:
      docker_int:
        ipv4_address: 10.172.10.13
    expose:
      - "6379"
    hostname: testflinger-db

    volumes:
      - db_data:/var/lib/redis

    environment:
      - REDIS_REPLICATION_MODE=master

    command: [
      "redis-server",
      "--bind 0.0.0.0",
      "--maxmemory 4096mb",
      "--maxmemory-policy allkeys-lfu"
    ]

  api:
    depends_on:
      - db
    build:    # build image w/ deps
      context: .
      dockerfile: testflinger-api
    init: true
    restart: unless-stopped

    networks:
      docker_int:
        ipv4_address: 10.172.10.12
    expose:
      - "8000"
    ports:
      - "10.245.130.9:8000:8000"
    hostname: testflinger-api

    # for secrets
    tmpfs:
      - /run

    secrets:
      - source: testflinger_secret
        target: testflinger_secret
        mode: 0440

    volumes:
      - api_data:/data/testflinger

    command: "gunicorn --bind 0.0.0.0:8000 testflinger:app" 

  agent:
    depends_on:
      - api
    # build image w/ deps
    build: 
      context: .
      dockerfile: testflinger-agent
    stdin_open: true
    tty: true
    restart: unless-stopped

    networks:
      needham_ext:
        ipv4_address: 10.245.128.10
      docker_int:
        ipv4_address: 10.172.10.10
    hostname: testflinger-agent

    # for secrets
    tmpfs:
      - /run

    secrets:
      - source: ubuntu_secret
        target: ubuntu_secret
        mode: 0440

    volumes:
      - agent_data:/data/testflinger-agent
      - snappy_data:/data/snappy-device-agents

    command: "/opt/tf-entrypoint.sh"

    # healthcheck:
    #   test: ["CMD", "ubuntu", "ping", "-h", "127.0.0.1", "--silent"]
    #   interval: 3s
    #   retries: 5
    #   start_period: 30s

  cli:
    depends_on:
      - agent
    # build image w/ deps
    build: 
      context: .
      dockerfile: testflinger-cli
    stdin_open: true
    tty: true
    restart: unless-stopped

    networks:
      needham_ext:
        ipv4_address: 10.245.128.11
      docker_int:
        ipv4_address: 10.172.10.11
    hostname: testflinger-cli

    secrets:
      - ubuntu_secret
      - testflinger_secret

    volumes:
      - cli_data:/data/testflinger-cli

    command: "/opt/tf-entrypoint.sh"

  # logstash:
  #     depends_on:
  #       - cli
  #     labels:
  #       com.example.service: "logstash"
  #       com.example.description: "For logging data"
  #     image: logstash

  #     networks:
  #       docker_int:
  #         ipv4_address: 10.172.10.14
  #     expose:
  #       - "5959"
  #     hostname: testflinger-log

  #     volumes:
  #       - log_data:/var

  #     command: "logstash -f /logstash_dir/logstash.conf"

networks:
  docker_int:
    driver: bridge
    driver_opts:
        parent: docker0
    ipam:
      config:
        - subnet: "10.172.10.1/24"
          # gateway: 10.172.10.1

  needham_ext:
    driver: macvlan
    driver_opts:
        parent: eno2
    ipam:
      config:
        - subnet: "10.245.128.0/22"
          # gateway: 10.245.128.1

secrets:
  ubuntu_secret:
    external: true
  testflinger_secret:
    external: true

volumes:
  db_data: {}
  api_data: {}
  agent_data: {}
  snappy_data: {}
  cli_data: {}
  # log_data: {}