path.home: ["/usr/share/filebeat"]

filebeat.inputs:
- type: log
  enabled: true
  paths:
    - "/var/log/sut-agent/"
  encoding: utf-8
  # exclude_lines: ["^DBG"]
  # include_lines: ["^ERR", "^WARN"]
  scan_frequency: 5s

- type: filestream
  enabled: false
  paths:
    - "/var/log/sut-agent/"
  encoding: utf-8
  # exclude_lines: ["^DBG"]
  # include_lines: ["^ERR", "^WARN"]
  prospector.scanner.check_interval: 5s
  prospector.scanner.include_files: ["/var/log/sut-agent/*"]
  prospector.scanner.exclude_files: ["/var/log/sut-agent/init_agent"]

- type: container
  enabled: true
  paths:
    - "/var/lib/docker/containers/*/*.log"

filebeat.modules:
- module: elasticsearch
  enabled: true
  server:
    enabled: true

- module: redis
  log:
    enabled: true
    var.paths: ["/var/log/redis/redis-server.log*"]

  # slowlog:
  #   enabled: true
  #   var.hosts: ["10.172.10.13:6379"]

- module: system
  syslog:
    enabled: true
    var.paths: ["/var/log/sut-agent/*"]

output.elasticsearch:
  hosts: ["http://10.172.10.14:9200"]

setup.kibana:
  hosts: ["http://10.172.10.15:5601"]